### ISSUE TITLE
vm_manager block in crm configure

### ISSUE THREAD

**Issue by dupremathieu** [seapath/vm_manager#33]
**Describe the bug**
During *create*, *clone* and *enable* commands, if *crm_config_cmd* is set to None by Ansible, `crm configure` will be run without attribute. As a result, `crm` enter in interactive mode and block vm_manager.

**To Reproduce**
Create a VM with Ansible with crm_config_cmd set to none.
Or enable a VM with _crm_config_cmd metadata defined but with no value.

**Comment by insatomcat** [comment]
Fixed by #32
